apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../crd
- ../rbac
- ../manager
- ../prometheus

images:
- name: kuberay/operator
  newName: kuberay/operator
  newTag: v0.4.0

